### ISSUE TITLE
balena push in Raspberry 3 tutorial fails: "could not load any valid magic files"

### ISSUE THREAD

**Issue by saintaardvark** [balena-io/balena-cli#1596]
- **balena CLI version:** e.g. 11.25.2
- **Operating system version:** Fedora 31 (also tested with Debian 9.1)
- **32/64 bit OS and processor:** 64-bit OS and processor
- **Install method:** zip
- **If npm install, Node.js and npm version:** N/A

---
Hi there -- as reported in [this forum post](https://forums.balena.io/t/fail-to-push-application-to-balena-cloud/61043/2), I'm having problems pushing an application with `balena push`; using version 11.25.2, it fails with the error "could not load any valid magic files".  This does *not* happen with version 11.21.5 (an older version of the CLI I picked at random).  Details follow.

Following [the Raspberry Pi 3 tutorial](https://www.balena.io/docs/learn/getting-started/raspberrypi3/nodejs/), I created an app named `Test`; I downloaded [the balena-node-hello-world-master repo](https://github.com/balenalabs/simple-server-node/archive/master.zip) and unzipped it; and ran `balena push Test` from within the new directory.  Here's what I saw (running again with `DEBUG=1` exported):

```
12:08 $ balena version
[debug] original argv0="balena" argv=[/home/aardvark/balena-cli-11.25.2/balena,/snapshot/versioned-source/bin/balena,version] length=3
[debug] new argv=[/home/aardvark/balena-cli-11.25.2/balena,/snapshot/versioned-source/bin/balena,version] length=3
11.25.2
✔ ~/dev/balena-node-hello-world-master 
12:12 $ balena apps
[debug] original argv0="balena" argv=[/home/aardvark/balena-cli-11.25.2/balena,/snapshot/versioned-source/bin/balena,apps] length=3
ID      APP NAME DEVICE TYPE  ONLINE DEVICES DEVICE COUNT
1578870 Test     raspberrypi3 1              1
✔ ~/dev/balena-node-hello-world-master 
12:12 $ balena push Test
[debug] original argv0="balena" argv=[/home/aardvark/balena-cli-11.25.2/balena,/snapshot/versioned-source/bin/balena,push,Test] length=4
[debug] Using . as build source
could not load any valid magic files!

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For CLI bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/
```
Since Fedora comes with SELinux enabled, I tried turning that off but got the same result.  I also got the same result when trying this on a Debian 9.11 machine I have.

Other commands seem to work on both Linux distros: logging in, listing apps and devices, and showing device logs.

If I try this with version 11.21.5, it works on both Fedora and Debian (showing with debugging turned off to keep the noise down):

```
✔ ~/dev/balena-node-hello-world-master 
12:16 $ balena version; balena push Test
11.21.5
[Info]     Starting build for Test, user gh_saintaardvark
[Info]     Dashboard link: https://dashboard.balena-cloud.com/apps/1578870/devices
[Info]     Building on arm03
[Info]     Pulling previous images for caching purposes...
[Success]  Successfully pulled cache images
[main]     Step 1/7 : FROM balenalib/raspberrypi3-node:10-stretch-run
[main]      ---> 3ee2d8b55586
[main]     Step 2/7 : WORKDIR /usr/src/app
[main]     Using cache
[main]      ---> 21688d5d98d2
[main]     Step 3/7 : COPY package.json package.json
[main]     Using cache
[main]      ---> f3c32eb12f3d
[main]     Step 4/7 : RUN JOBS=MAX npm install --production --unsafe-perm && npm cache verify && rm -rf /tmp/*
[main]     Using cache
[main]      ---> f87ce5f1cb27
[main]     Step 5/7 : COPY . ./
[main]     Using cache
[main]      ---> ab732f800d8e
[main]     Step 6/7 : ENV UDEV=1
[main]     Using cache
[main]      ---> a69aa32a5d40
[main]     Step 7/7 : CMD ["npm", "start"]
[main]     Using cache
[main]      ---> c8f294f3ec54
[main]     Successfully built c8f294f3ec54
[Info]     Uploading images
[Success]  Successfully uploaded images
[Info]     Built on arm03
[Success]  Release successfully created!
[Info]     Release: f657e7982418a0663e0bb0aa5fa09dc5 (id: 1245320)
[Info]     ┌─────────┬────────────┬────────────┐
[Info]     │ Service │ Image Size │ Build Time │
[Info]     ├─────────┼────────────┼────────────┤
[Info]     │ main    │ 199.18 MB  │ < 1 second │
[Info]     └─────────┴────────────┴────────────┘
[Info]     Build finished in 12 seconds
                            \
			     \
			      \\
			       \\
			        >\/7
			    _.-(6'  \
			   (=___._/` \
			        )  \ |
			       /   / |
			      /    > /
			     j    < _\
			 _.-' :      ``.
			 \ r=._\        `.
			<`\\_  \         .`-.
			 \ r-7  `-. ._  ' .  `\
			  \`,      `-.`7  7)   )
			   \/         \|  \'  / `-._
			              ||    .'
			               \\  (
			                >\  >
			            ,.-' >.'
			           <.'_.''
			             <'
```

Thanks very much for any help you can give.  If you need any further information, please let me know.

**Comment by pdcastro** [comment]
Thanks for reporting this issue. I gather that the error message `"could not load any valid magic files!"` comes from the [mmmagic library](https://github.com/mscdex/mmmagic/blob/v0.5.3/deps/libmagic/src/apprentice.c#L706), which is a dependency introduced in CLI version 11.25.0 in order to automatically convert text file line endings from Windows CRLF to Unix LF.

Almost certainly, **CLI versions 11.24.0 or older are not affected, so right now the suggested workaround is to downgrade the CLI.** We are investigating the issue further and will fix it shortly.

**Comment by srlowe** [comment]
Note, have queried distribution support with package owner.
https://github.com/mscdex/mmmagic/issues/142

**Comment by srlowe** [comment]
@saintaardvark This should now be fixed in latest release.  Were you installing the CLI from withing a docker container?  I'm currently trying to understand what went wrong.  Thank you.

**Comment by saintaardvark** [comment]
Hi @srlowe -- I can confirm that this does now work for me, and the new release lets me run `balena push` without any problems.

I was running this from a terminal on my laptop, which runs Fedora 31; it was not in a Docker container.  I was following the [zip file instructions here](https://github.com/balena-io/balena-cli/blob/master/INSTALL.md#standalone-zip-package):  I downloaded the CLI zipfile, uncompressed it, then set the `PATH` in my shell to include that directory.  I ran into problems at the `balena push [app]` step detailed in the [Raspberry Pi tutorial](https://www.balena.io/docs/learn/getting-started/raspberrypi3/nodejs/).

I hope that helps, but let me know if you need any further info.

**Comment by pdcastro** [comment]
@srlowe, by the way, the issue could also be reproduced with the Dockerfile that we provide as a reference for the CLI's NPM installation on Linux / Ubuntu. Search the following page for "sample Dockerfile": https://github.com/balena-io/balena-cli/blob/master/INSTALL.md#npm-installation

**Comment by pdcastro** [comment]
Note for anyone reaching this issue: we've found that the problem remains specifically on the **standalone zip installation for Windows.** Check issue #1607 for more details.
