### ISSUE TITLE
Anti-virus and windows detect balena.exe as rare threat

### ISSUE THREAD

**Issue by Biorix** [balena-io/balena-cli#1820]
- **balena CLI version:**  11.33.3
- **Operating system** version: Windows 10 : 64-bit Windows on 64-bit Intel processor
- **Install method:**  zip standalone (balena-cli-v11.33.3-windows-x64-standalone.zip)

---

AVG anti-virus immediately block the .exe and send it to their lab for analysis. It returned as dangerous and has been quarantine.\
Windows is also blocking it itself.

The threat name for AVG is "Custody" and "DS#EvoGEn||algo"

I didn't find a proper log of the analysis within the sub-folders of AVG

I want to add the .exe to exception but since I haven't found any ticket regarding this issue I need to make sure it safe and that my download has not been corrupted somehow.

**Comment by pdcastro** [comment]
@Biorix, thank you for reporting this issue. I have removed the `balena-cli-v11.33.3-windows-x64-standalone.zip` from download in the releases page while we investigate this issue. What I have found so far:

* I installed the AVG antivirus from `avg.com` on a Windows 10 Home (Build 18363) laptop. The laptop also has the built-in Microsoft "Windows Security" application that includes a "Virus & threat protection" scanner.
* I updated both antivirus applications to the latest "virus threat definitions" and "security intelligence" as of approximately 9pm UTC on 12 May 2020.
* I downloaded the balena CLI zip packages and executable installers for Windows for releases v11.33.2 and v11.33.3 and scanned them with both antivirus apps.

Results:

balena-cli asset | AVG antivirus | Microsoft Windows Security
--- | --- | ---
v11.33.2 executable installer | Pass | Pass
v11.33.2 zip file | Pass | Pass
v11.33.2 zip file (unzipped) | Pass | Pass
v11.33.2 "C:\Program Files\balena-cli" | Pass | Pass
v11.33.3 executable installer | Pass | Pass
v11.33.3 zip file | Pass | Pass
v11.33.3 zip file (unzipped) | Fail on `balena.exe` | Pass
v11.33.3 "C:\Program Files\balena-cli" | Pass | Pass

I am now trying to isolate the difference between the versions and installers that could explain the AVG fail, to try and conclude whether this could be a false positive.

**Comment by pdcastro** [comment]
@Biorix, I believe it was a false positive, because adding a blank line to the CLI's `package.json` file in pull request #1821 (release v11.33.4) was sufficient to prevent AVG from reporting `balena.exe` as malware. Nothing else was changed, in particular no dependencies were changed (the `npm-shrinkwrap.json` file was not changed). The theory is that a sequence of bytes in the `balena.exe` binary was coincidentally equal to some threat "signature" in AVG's threat database. In which case, "this issue was fixed in CLI release v11.33.4". Thanks again for reporting it.

**Comment by Biorix** [comment]
@pdcastro Thank you for the support
I tried the [standalone V11.33.4](https://github.com/balena-io/balena-cli/releases/download/v11.33.4/balena-cli-v11.33.4-windows-x64-standalone.zip) and still have a message from windows and AVG

My windows version is Windows 10 Home v1903, build 18362.778
My AVG version is 20.2.3116 (version 20.2.5130.572)
Viral data base is 200512-0

Once I started the .exe AVG has again send the file to their lab since they doesn't have the signature yet and return it as threat.
If I analyze the zip, AVG says it's OK but if the I try to open the .exe or analyze it's quarantined  
The threat name this time is *FileRepMalware*. It does look like a false positive since the name change every time. 

Let me know if you need more details

**Comment by pdcastro** [comment]
I am sure that, yesterday, at one point my AVG installation had a virus definition database that reported CLI v11.33.3 as a threat, but did ***not*** report v11.33.4 as a threat. I have now updated the virus definitions (Virus definitions "ver 200513-0 of 13 May 2020 23:22, AVG app "ver. 20.3.3120 - build 20.3.5200.573") and it reported v11.33.4 as a threat.

I have also reported this issue upstream, on the repo that provides the patched Node.js version that gets bundled in the balena-cli standalone zip packages:
* Issue https://github.com/zeit/pkg-fetch/issues/93
* File `"uploaded-v2.6-node-v10.17.0-win-x64"` at https://github.com/zeit/pkg-fetch/releases

And I have reported it to AVG as well at: https://www.avg.com/en-ww/false-positive-file-form

We should be cautious though. As a precaution, while this issue is investigated, I am removing the standalone zip package for Windows from the releases page. Thank you again for reporting this issue.

**Comment by pdcastro** [comment]
I swear with my hand on the bible that the AVG application keeps changing its mind about `balena.exe` being a threat, even with the same app version and virus definition version. Using AVG Virus definitions "ver 200513-0 of 14 May 2020 11:53", I am getting a 50% hit-and-miss threat report rate, if I give some 10 minutes between file scans. It could be that AVG is buggy and unreliable, but it could also be that it is a sophisticated malware/virus that manages to temporarily disguise itself from detection (and which would have infected the laptop on which I am running the tests).

Right now, AVG is reporting that balena CLI v11.33.3 and v11.33.4 are threats (FileRepMalware), but that v11.34.0 and v11.35.0 (draft release) are not threats. But they all bundle the same upstream patched Node.js executable (issue zeit/pkg-fetch#93) and the same dependency packages ([npm-shrinkwrap.json](https://github.com/balena-io/balena-cli/blob/v11.34.0/npm-shrinkwrap.json)).

Also, yesterday with virus definitions "ver 200513-0 of 13 May 2020 23:22", AVG was reporting that the upstream executable (zeit/pkg-fetch#93) contained Win64:MdeClass "high severity threat", but today with virus definitions "ver 200513-0 of 14 May 2020 11:53" (same version but different date), AVG says _"Looking good! No threats found."_

I don't know what to make of it... :-/

**Comment by Biorix** [comment]
I put the file through [Kaspersky online scan tool](https://opentip.kaspersky.com/) and it didn't find anything.
I'm inclined to think the Kaspersky analysis is more reliable than AVG free but I might be wrong.

Here is the result for V11.33.4
* for the [zip file](https://opentip.kaspersky.com/AA7EB61C1239529072CDE20F47545CA08988C1302598D00F9B7E1416D6F6CCC5/)
* for [.exe file](https://opentip.kaspersky.com/78C74D4E4EDB633B2E6579DB23CEA5ED97E3684DD1835E9DD4A22EB33B2CE929/) alone

**Comment by pdcastro** [comment]
Good hint @Biorix, the Karspersky online scanner also accepts URLs, so in some cases the scan can be done without downloading the files to any laptop. These URLs are reported good:
* Upstream patched Node.js executable: ✅ https://opentip.kaspersky.com/https%3A%2F%2Fgithub.com%2Fzeit%2Fpkg-fetch%2Freleases%2Fdownload%2Fv2.6%2Fuploaded-v2.6-node-v10.17.0-win-x64/
* Public URL to balena CLI v11.35.0 Windows zip package: ✅ https://opentip.kaspersky.com/https%3A%2F%2Fgithub.com%2Fbalena-io%2Fbalena-cli%2Freleases%2Fdownload%2Fv11.35.0%2Fbalena-cli-v11.35.0-windows-x64-standalone.zip/

Re Windows zip package for CLI v11.35.0, including the `balena.exe` file on its own:
* AVG on Windows (Virus definitions "ver 200513-0 of 14 May 2020 13:16") does not "currently" report any threats.
* Using a Mac laptop (considering that the Windows laptop might have been compromised) to download the zip package and upload `balena.exe`, Karspersky did not find any threats: https://opentip.kaspersky.com/E90275A40B5D5A387B69E407B9C64F743317AD39B155D07CC42530260427DBCB/

**Comment by pdcastro** [comment]
Just got this e-mail from AVG support:

> From: AVG Support <support@help.avg.com>
> Subject: AVG: False positive file balena-standalone-v11.34.0.zip - Request #10742396 ref:_00Db0Z3Sf._5000N2CHKD6:ref
>
> Hello,
>
> Thank you for contacting AVG.
>
> Please accept our apologies for the inconvenience caused. The detection by AVG was incorrect and was removed in a recent AVG update, please wait at least 24 hours.
>
>If the detection persists, please reply to this e-mail and:
>
> 1. Attach the screenshot including the detection dialog, with See details in the bottom-right corner displayed. To create a screenshot, please refer to the following link.
> [Creating a screenshot](https://support.avg.com/SupportArticleView?urlName=AVG-Create-screenshot)
>
> 2. Attach a screenshot of your virus database version in AVG.
>
> Open AVG ▸ Menu ▸ About
>
> Please do not hesitate to contact AVG at any time with further inquiries.
>
> Thank you for your patience and cooperation, we appreciate it.
>
> Best regards,
>
> AVG Customer Care

**Comment by Biorix** [comment]
So I guess it's safe to use it
I'm closing the issue
Thanks @pdcastro !
